spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?user=postgres.torvyxktjroqkpzgibpg&password=VgMJEpNarpEW5m2n
spring.datasource.username=postgres
spring.datasource.password=VgMJEpNarpEW5m2n

spring.application.name=demo
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true